environments:
  dev: {}
  prod: {}
---
releases:
  - name: traefik
    chart: traefik/traefik
    version: 37.1.0
    namespace: traefik
    createNamespace: true
    values:
      - ./{{ .Environment.Name }}-values.yaml
---
helmfiles:
  - path: ./traefik-mics/helmfile.yaml
