ingressRoute:
  dashboard:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.tls: "true"
    matchRule: Host(`dashboard.home.ichi-h.com`)
    entryPoints:
      - web
    middlewares:
      - name: traefik-dashboard-auth

persistence:
  enabled: true
  name: cloudflareResolver
  storageClass: traefik-local-storage
  volumeName: traefik-pv
  path: /data

certificatesResolvers:
  cloudflareResolver:
    acme:
      email: "{{ .Values.cloudflare.email }}"
      storage: /data/acme.json
      dnschallenge:
        provider: cloudflare

nodeSelector:
  role: application

env:
  - name: CF_API_EMAIL
    value: "{{ .Values.cloudflare.email }}"
  - name: CF_DNS_API_TOKEN
    value: "{{ .Values.cloudflare.dnsApiToken }}"

extraObjects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: traefik-dashboard-auth-secret
    type: kubernetes.io/basic-auth
    stringData:
      username: admin
      password: "{{ .Values.traefik.basicAuthPasswd }}"

  - apiVersion: traefik.io/v1alpha1
    kind: Middleware
    metadata:
      name: traefik-dashboard-auth
    spec:
      basicAuth:
        secret: traefik-dashboard-auth-secret
