ingressRoute:
  dashboard:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.tls: "true"
    matchRule: Host(`dashboard.home.ichi-h.com`)
    entryPoints:
      - web
    middlewares:
      - name: traefik-dashboard-auth

persistence:
  enabled: true
  name: cloudflare-resolver
  storageClass: traefik
  path: /data

certificatesResolvers:
  cloudflare-resolver:
    acme:
      email: "{{ .Values.cloudflare.email }}"
      storage: /data/acme.json
      dnschallenge:
        provider: cloudflare

nodeSelector:
  role: application

env:
  - name: CF_API_EMAIL
    value: "{{ .Values.cloudflare.email }}"
  - name: CF_DNS_API_TOKEN
    value: "{{ .Values.cloudflare.dnsApiToken }}"
