{{- if eq .Values.storageType "local" }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: loki
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
{{- end }}
