apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistentVolume.name }}
spec:
  capacity:
    storage: {{ .Values.persistentVolume.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: loki-local-storage
  local:
    path: {{ .Values.persistentVolume.local.path }}
  {{- with .Values.persistentVolume.nodeAffinity }}
  nodeAffinity:
    {{- toYaml . | nindent 8 }}
  {{- end }}
