apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud-ing
spec:
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nextcloud-svc
            port:
              name: http
