{{- if eq .Values.storageType "local" }}
{{- range .Values.persistentVolumeClaims }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-{{ .name }}-pv
spec:
  capacity:
    storage: {{ .storage }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nextcloud-{{ .name }}
  local:
    path: {{ .pv.localPath }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: role
              operator: In
              values:
                - application
{{- end }}
{{- end }}
