storageType: local # local or ceph
persistentVolume:
  name: loki-pv
  size: 128Mi
  local:
    path: /mnt/k8s/volumes/loki
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: role
              operator: In
              values:
                - application
