keys:
  - &tokiwa age1dgek4suae02cv73wc3vtdprz76mrvrnqm5j7a38vg43lw9c6mp4ssa5aev
  - &hanaakari age19twem85mlu9sm5nthkuty6ynmul9dssyd9sx7nq9gzhgfsjht3fs9pwlcl
  - &yomogi age1m3w90medfuuzgqsv9k25nxd4yggtkzz84r8pz8mg4nqvyn092p2syva3k9
  - &yomosugara age1qk59lxkezdasvsy75rp9s04w5uxlt3vhu5cd8pn0mzf3593c64mqlpkzzp
  - &fujibakama age1cvfeerg2qryzpxdryrjmchy087fpprhll3kl7jmaech95wghmujq5gkj84
creation_rules:
  - path_regex: hosts/tokiwa/secrets.yaml$
    key_groups:
      - age:
          - *tokiwa
  - path_regex: hosts/hanaakari/secrets.yaml$
    key_groups:
      - age:
          - *hanaakari
  - path_regex: hosts/yomogi/secrets.yaml$
    key_groups:
      - age:
          - *yomogi
  - path_regex: hosts/yomosugara/secrets.yaml$
    key_groups:
      - age:
          - *yomosugara
  - path_regex: hosts/fujibakama/secrets.yaml$
    key_groups:
      - age:
          - *fujibakama
