s3:
    access-key-id: ENC[AES256_GCM,data:qQ+jjx4=,iv:VcwKwrmZXj+DxBs/YgcgpL9gxENk+WHpMrrGOkuJKtw=,tag:ahm4Zsnzb2a2efFKL1Xxyg==,type:str]
    secret-access-key: ENC[AES256_GCM,data:dZduwdSMFqM=,iv:YW98Oxd2QNFKHGFCh3GIWSTv6KoU/DdIhUwq8lF+yDE=,tag:21EZktZhzJUszqeViM+/Xw==,type:str]
sops:
    age:
        - recipient: age1h0sp353y3qnkv40dtremtl7e6uxp5dx35m4r4tr78fe8fle0m9eqhd2g78
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NWNSUk1PNmoxTVRLVVky
            RFBOK3lFLzdKSnRuVm5OaXBDVWlSWlIvSUJnCklmVzFHUGJhRDduc3g3c2hpdXRP
            SVBETjFoMHMwMFVJT1FCUEQyMnJUTUUKLS0tIDd2dUpRemV2bFFBaHk3eXhsUDNY
            TzNQaGFSbDNzKzVjalFkc3pWeXFSOEEK8hOEBy8jA2zpEjw4JQApOKbG217B3T53
            OXfrGXz/h+prcDwkVtEhEKkckK9GWfdemLycHzvLhTSrQqCahFJ2Vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-11T02:52:54Z"
    mac: ENC[AES256_GCM,data:j41raMeyUmncVpEld6mz4An2xn83Pxczb9TuRIDePOmQlPukZp4ldO5N718VFekoCVvv22jZaSmAZvcdqLFM7n3QWjIsmkbjbNlB620zlpeWSUZMf/S/CMMhuxbkLqog/Y7L4pfeWQ1I6HYRlp6bPTNZ3KA/mtWTo8ZzWh5ANe8=,iv:M73Kpog72YdhSK8B2lyFPcKadQh4+oq11z0quKlBkhc=,tag:MaT1ewcFMUm3FH+6J2gRVA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
