apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data-pv
spec:
  capacity:
    storage: 128Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nextcloud-data-local-storage
  local:
    path: /mnt/k8s/volumes/shared/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: role
              operator: In
              values:
                - application
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-config-pv
spec:
  capacity:
    storage: 16Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nextcloud-config-local-storage
  local:
    path: /mnt/k8s/volumes/shared/config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: role
              operator: In
              values:
                - application
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-custom-apps-pv
spec:
  capacity:
    storage: 128Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nextcloud-custom-apps-local-storage
  local:
    path: /mnt/k8s/volumes/shared/custom_apps
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: role
              operator: In
              values:
                - application
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-themes-pv
spec:
  capacity:
    storage: 16Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nextcloud-themes-local-storage
  local:
    path: /mnt/k8s/volumes/shared/themes
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: role
              operator: In
              values:
                - application
