ingress:
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
  host: nextcloud.home.ichi-h.com

storageType: ceph

persistentVolumeClaims:
  - name: data
    storage: 50Gi
  - name: config
    storage: 16Mi
  - name: custom-apps
    storage: 128Mi
  - name: themes
    storage: 16Mi
