kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vaultwarden-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: vaultwarden-local-storage
  resources:
    requests:
      storage: {{ .Values.app.storage.size }}
