cephClusterSpec:
  storage:
    useAllNodes: false
    useAllDevices: false
    nodes:
      - name: hanaakari
        devices:
          - name: /dev/disk/by-id/ata-KIOXIA-EXCERIA_SATA_SSD_448FB2OAFWC6
  placement:
    all:
      nodeAffinity:
        required:
          nodeSelectorTerms:
            - matchExpressions:
                - key: role
                  operator: In
                  values:
                    - application

cephBlockPools:
cephObjectStores:
cephFileSystems:
  - name: myfs
    # see https://github.com/rook/rook/blob/master/Documentation/CRDs/Shared-Filesystem/ceph-filesystem-crd.md#filesystem-settings for available configuration
    spec:
      metadataPool:
        replicated:
          size: 1
      dataPools:
        - name: default
          replicated:
            size: 1
      metadataServer:
        activeCount: 1
        activeStandby: true
    storageClass:
      enabled: false
      isDefault: false
