repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: vector
    url: https://helm.vector.dev
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: vmware-tanzu
    url: https://vmware-tanzu.github.io/helm-charts

environments:
  dev: {}
  prod: {}

helmfiles:
  - ./src/releases/grafana/helmfile.yaml
  - ./src/releases/loki/helmfile.yaml
  - ./src/releases/minio/helmfile.yaml
  - ./src/releases/nextcloud/helmfile.yaml
  - ./src/releases/prometheus/helmfile.yaml
  - ./src/releases/vaultwarden/helmfile.yaml
  - ./src/releases/vector/helmfile.yaml
  - ./src/releases/velero/helmfile.yaml
