repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: vector
    url: https://helm.vector.dev
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: vmware-tanzu
    url: https://vmware-tanzu.github.io/helm-charts
  - name: traefik
    url: https://traefik.github.io/charts

environments:
  dev: {}
  prod: {}

helmfiles:
  - ./releases/grafana/helmfile.yaml
  - ./releases/loki/helmfile.yaml
  - ./releases/minio/helmfile.yaml
  - ./releases/nextcloud/helmfile.yaml
  - ./releases/prometheus/helmfile.yaml
  - ./releases/traefik/helmfile.yaml
  - ./releases/vaultwarden/helmfile.yaml
  - ./releases/vector/helmfile.yaml
  - ./releases/velero/helmfile.yaml
