repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: vector
    url: https://helm.vector.dev
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: loki
    chart: grafana/loki
    version: 6.38.0
    values:
      - deploymentMode: SingleBinary<->SimpleScalable
        loki:
          auth_enabled: false
          containerSecurityContext:
            readOnlyRootFilesystem: false
          podSecurityContext:
            fsGroup: 0
            runAsNonRoot: false
            runAsUser: 0
          commonConfig:
            replication_factor: 1
          storage:
            type: filesystem
          commonStorageConfig:
            type: filesystem
          persistence:
            enabled: true
          rulerConfig:
            storage:
              type: local
          schemaConfig:
            configs:
              - from: "2025-08-01"
                store: tsdb
                object_store: filesystem
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h
        singleBinary:
          replicas: 1
          extraArgs: ["-config.expand-env=true"]
          persistence:
            enabled: true
            storageClass: loki-local-storage
            size: 128Mi
          nodeSelector:
            role: application
        gateway:
          nodeSelector:
            role: application
        table_manager:
          retention_deletes_enabled: true
          retention_period: 24h
  - name: grafana
    chart: grafana/grafana
    version: 9.4.0
    values:
      - service:
          type: NodePort
        nodeSelector:
          role: application
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: "Prometheus"
                type: prometheus
                access: proxy
                url: http://prometheus-server
              - name: "Loki"
                type: loki
                access: proxy
                url: http://loki-gateway
  - name: vector
    chart: vector/vector
    version: 0.45.0
    values:
      - role: "Agent"
        workloadType: "DaemonSet"
        service:
          enabled: false
        tolerations:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: NoSchedule
          - key: node-role.kubernetes.io/master
            operator: Exists
            effect: NoSchedule
        extraVolumes:
          - name: var-lib-docker-containers
            hostPath:
              path: /var/lib/docker/containers
        extraVolumeMounts:
          - name: var-lib-docker-containers
            mountPath: /var/lib/docker/containers
            readOnly: true
        customConfig:
          data_dir: /vector-data-dir
          sources:
            kubernetes_logs:
              type: kubernetes_logs
              auto_partial_merge: true
              include_paths_glob_patterns:
                - /var/log/containers/*.log
                - /var/log/pods/*/*/*.log
          sinks:
            loki_logs:
              type: loki
              inputs: ["kubernetes_logs"]
              encoding:
                codec: json
              endpoint: http://loki-gateway.default.svc.cluster.local
              labels:
                job: vector
                cluster: kubernetes
              batch:
                max_bytes: 102400
                timeout_secs: 5
              request:
                timeout_secs: 30
                retry_attempts: 5
                retry_max_duration_secs: 300
                retry_initial_backoff_secs: 1
                retry_max_delay_secs: 30
  - name: prometheus
    chart: prometheus-community/prometheus
    version: 27.32.0
    values:
      - server:
          persistentVolume:
            size: 128Mi
            storageClass: prometheus-server-local-storage
          nodeSelector:
            role: application
        alertmanager:
          persistence:
            size: 128Mi
            storageClass: prometheus-alertmanager-local-storage
