storageType: local # local or ceph

persistentVolume:
  alertmanager:
    capacity:
      storage: 128Mi
  server:
    capacity:
      storage: 128Mi
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: role
              operator: In
              values:
                - application
