environments:
  dev: {}
  prod: {}
---
releases:
  - name: velero
    namespace: velero
    chart: vmware-tanzu/velero
    version: 10.1.1
    secrets:
      - ./{{ .Environment.Name }}-secrets.yaml
    values:
      - ./{{ .Environment.Name }}-values.yaml
