configuration:
  provider: aws
  backupStorageLocation:
    name: backup-bucket-s3
    bucket: home-server-backup.ichi-h
    default: true
    config:
      region: ap-northeast-1
  volumeSnapshotLocation:
    name: backup-bucket-s3
    config:
      region: ap-northeast-1
initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.12.2
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins
# schedules:
#   app-backup:
#     disabled: true
#     schedule: "0 0 * * *"
#     useOwnerReferencesInBackup: false
#     paused: false
#     skipImmediately: false
#     template:
#       ttl: "240h"
#       storageLocation: default
#       includedNamespaces:
#       - foo
#       # See: https://velero.io/docs/v1.14/resource-filtering/#excludes
#       excludedNamespaceScopedResources:
#       - persistentVolumeClaims
#       excludedClusterScopedResources:
#       - persistentVolumes
