persistentVolume:
  name: traefik-pv
  size: 128Mi
  local:
    path: /mnt/k8s/volumes/traefik
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: role
              operator: In
              values:
                - application
