role: "Agent"
workloadType: "DaemonSet"
service:
  enabled: false
tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule
extraVolumes:
  - name: var-lib-docker-containers
    hostPath:
      path: /var/lib/docker/containers
extraVolumeMounts:
  - name: var-lib-docker-containers
    mountPath: /var/lib/docker/containers
    readOnly: true
customConfig:
  data_dir: /vector-data-dir
  sources:
    kubernetes_logs:
      type: kubernetes_logs
      auto_partial_merge: true
      include_paths_glob_patterns:
        - /var/log/containers/*.log
        - /var/log/pods/*/*/*.log
  sinks:
    loki_logs:
      type: loki
      inputs: ["kubernetes_logs"]
      encoding:
        codec: json
      endpoint: http://loki-gateway.default.svc.cluster.local
      labels:
        job: vector
        cluster: kubernetes
      batch:
        max_bytes: 102400
        timeout_secs: 5
      request:
        timeout_secs: 30
        retry_attempts: 5
        retry_max_duration_secs: 300
        retry_initial_backoff_secs: 1
        retry_max_delay_secs: 30
