[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']

[[plugins]]
repo    = 'lambdalisue/glyph-palette.vim'
depends = ['fern.vim']

[[plugins]]
repo    = 'lambdalisue/nerdfont.vim'
depends = ['fern.vim']

[[plugins]]
repo    = 'lambdalisue/fern-renderer-nerdfont.vim'
depends = ['fern.vim']

[[plugins]]
repo    = 'lambdalisue/fern-git-status.vim'
depends = ['fern.vim']

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'lambdalisue/fern.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'Townk/vim-autoclose'
