apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden-deploy
  labels:
    role: {{ .Values.app.metadata.labels.role }}
spec:
  replicas: 1
  selector:
    matchLabels:
      role: {{ .Values.app.metadata.labels.role }}
  template:
    metadata:
      labels:
        role: {{ .Values.app.metadata.labels.role }}
        app: vaultwarden
    spec:
      nodeSelector:
        role: {{ .Values.app.metadata.labels.role }}
      containers:
        - name: vaultwarden
          image: vaultwarden/server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: DOMAIN
              value: {{ if .Values.enableTls }}https{{ else }}http{{ end }}://{{ .Values.ingress.host }}
            - name: PASSWORD_HINTS_ALLOWED
              value: "false"
            - name: SMTP_HOST
              value: {{ .Values.email.smtpHost }}
            - name: SMTP_PORT
              value: "{{ .Values.email.smtpPort }}"
            - name: SMTP_FROM
              value: {{ .Values.email.smtpFrom }}
            - name: SMTP_USERNAME
              value: {{ .Values.email.smtpUsername }}
            - name: SMTP_PASSWORD
              value: {{ .Values.email.smtpPasswd }}
          volumeMounts:
            - name: vw-data
              mountPath: /data
          resources:
            limits:
              cpu: "200m"
              memory: "256Mi"
            requests:
              cpu: "50m"
              memory: "64Mi"
      volumes:
        - name: vw-data
          persistentVolumeClaim:
            claimName: vaultwarden-pvc
