apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden-deploy
  labels:
    role: {{ .Values.metadata.labels.role }}
spec:
  replicas: 1
  selector:
    matchLabels:
      role: {{ .Values.metadata.labels.role }}
  template:
    metadata:
      labels:
        role: {{ .Values.metadata.labels.role }}
        app: vaultwarden
    spec:
      nodeSelector:
        role: {{ .Values.metadata.labels.role }}
      containers:
        - name: vaultwarden
          image: vaultwarden/server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: DOMAIN
              value: {{ .Values.app.domain }}
          volumeMounts:
            - name: vw-data
              mountPath: /data
          resources:
            limits:
              cpu: "200m"
              memory: "256Mi"
            requests:
              cpu: "50m"
              memory: "64Mi"
      volumes:
        - name: vw-data
          persistentVolumeClaim:
            claimName: vaultwarden-pvc
