apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vaultwarden-ing
spec:
  rules:
  - host: {{ .Values.app.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vaultwarden-svc
            port:
              name: http
