apiVersion: v1
kind: Service
metadata:
  name: vaultwarden-svc
spec:
  type: ClusterIP
  selector:
    app: vaultwarden
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
