[font]
size = 20

[font.bold]
family = "HackGenNerd Console"
style = "Bold"

[font.bold_italic]
family = "HackGenNerd Console"
style = "Bold Italic"

[font.italic]
family = "HackGenNerd Console"
style = "Italic"

[font.normal]
family = "HackGenNerd Console"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "buttonless"
opacity = 0.8
startup_mode = "SimpleFullscreen"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 5
y = 5
