environments:
  dev: {}
  prod: {}
---
releases:
  - name: grafana
    chart: ./chart
    version: 0.1.0
    secrets:
      - ../../secrets/{{ .Environment.Name }}-secrets.yaml
    values:
      - ./{{ .Environment.Name }}-values.yaml
