nodeSelector:
  role: application

ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
  path: /
  pathType: Prefix
  hosts:
    - grafana.home.ichi-h.com

persistence:
  type: pvc
  enabled: true
  storageClassName: grafana
  accessModes:
    - ReadWriteOnce
  size: 10Gi
